theme: bulma-clean-theme


## main config
lang: en
title: Petersweb
tagline: Bulma Clean Theme
email: your-email@domain.com
description: >
  The demo site for risk marketing
baseurl: ""
url: ""

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

sass:
  style: compressed

author: 
  twitter: TBC
lang: en_GB
logo: #
twitter:
  username: 
  card: 
facebook:
  publisher: 
social:
  name: 
  links:
    - https://www.petersweb.me.uk

permalink: pretty
#favicon: /path/to/favicon.png
#hide_share_buttons: true
#theme_color: '#eeeeee'
#fixed_navbar: top
#direction: one of <ltr, rtl, auto>, default: ltr

paginate: 5
paginate_path: "/blog/page:num"



exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

#google_analytics: UA-code-here

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: false
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Peter"
      layout: post
      image: https://via.placeholder.com/1200x800
      show_sidebar: true

markdown: kramdown
highlighter: rouge

footer_menu: example_footer_menu